# Testes com CBR antes de passar para o Jogo

In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

Codificação de Naipes para poder buscar pelo vizinho mais próximo

In [116]:
def codificar_naipes(x):
    print(x)
    if (x == 'ESPADAS'):
        return 1
    
    if (x == 'OURO'):
        return 2
    
    if (x == 'BASTOS'):
        return 3
    
    if (x == 'COPAS'):
        return 4

Tratamentos para o dataframe

In [117]:
df = pd.read_csv('dbtrucoimitacao_maos.csv', index_col='idMao').fillna(0)
colunas_string = [
    'naipeCartaAltaRobo', 'naipeCartaMediaRobo','naipeCartaBaixaRobo', 'naipeCartaAltaHumano','naipeCartaMediaHumano', 'naipeCartaBaixaHumano','naipePrimeiraCartaRobo', 'naipePrimeiraCartaHumano',	'naipeSegundaCartaRobo', 'naipeSegundaCartaHumano','naipeTerceiraCartaRobo', 'naipeTerceiraCartaHumano',
    ]
colunas_int = [col for col in df.columns if col not in colunas_string]
df[colunas_int] = df[colunas_int].astype('int')
# df[colunas_string] = df[colunas_string].any(axis=1)
# df[colunas_string] = df[colunas_string].apply(lambda x: print(x), axis=1)
# pd.get_dummies(df[colunas_string], prefix=colunas_string)
df.replace('ESPADAS', '1', inplace=True)
df.replace('OURO', '2', inplace=True)
df.replace('BASTOS', '3', inplace=True)
df.replace('COPAS', '4', inplace=True)
df[colunas_string] = df[colunas_string].astype('int')
# df.apply(abs)
df = df[(df >= 0).all(axis=1)]

Verificação da codificação de naipes

In [118]:
df[colunas_string]

naipeCartaAltaRobo  naipeCartaMediaRobo  naipeCartaBaixaRobo  \
idMao                                                                 
52                      1                    2                    3   
56                      1                    4                    1   
68                      1                    3                    3   
69                      1                    2                    1   
77                      2                    4                    1   
...                   ...                  ...                  ...   
7633                    3                    1                    3   
7668                    1                    2                    3   
7700                    3                    2                    4   
7706                    4                    3                    2   
7717                    1                    3                    1   

       naipeCartaAltaHumano  naipeCartaMediaHumano  naipeCartaBaixaHumano  \
idMao                                                                       
52                        2                      4                      2   
56                        1                      3                      1   
68                        4                      2                      4   
69                        3                      4                      3   
77                        3                      4                      3   
...                     ...                    ...                    ...   
7633                      3                      2                      3   
7668                      2                      2                      1   
7700                      2                      3                      4   
7706                      2                      2                      1   
7717                      1                      1                      2   

       naipePrimeiraCartaRobo  naipePrimeiraCartaHumano  \
idMao                                                     
52                          3                         4   
56                          1                         2   
68                          3                         3   
69                          1                         2   
77                          1                         4   
...                       ...                       ...   
7633                        3                         3   
7668                        3                         2   
7700                        4                         2   
7706                        2                         2   
7717                        1                         1   

       naipeSegundaCartaRobo  naipeSegundaCartaHumano  naipeTerceiraCartaRobo  \
idMao                                                                           
52                         2                        2                       1   
56                         4                        1                       1   
68                         3                        2                       1   
69                         2                        4                       1   
77                         4                        3                       2   
...                      ...                      ...                     ...   
7633                       3                        2                       1   
7668                       2                        2                       1   
7700                       3                        3                       2   
7706                       4                        2                       3   
7717                       1                        1                       3   

       naipeTerceiraCartaHumano  
idMao                            
52                            3  
56                            3  
68                            4  
69                            3  
77                            0  
...                  

In [119]:
for column in df.columns:
    print(column)

jogadorMao
cartaAltaRobo
cartaMediaRobo
cartaBaixaRobo
cartaAltaHumano
cartaMediaHumano
cartaBaixaHumano
primeiraCartaRobo
primeiraCartaHumano
segundaCartaRobo
segundaCartaHumano
terceiraCartaRobo
terceiraCartaHumano
ganhadorPrimeiraRodada
ganhadorSegundaRodada
ganhadorTerceiraRodada
quemPediuEnvido
quemPediuFaltaEnvido
quemPediuRealEnvido
pontosEnvidoRobo
pontosEnvidoHumano
quemNegouEnvido
quemGanhouEnvido
tentosEnvido
quemFlor
quemContraFlor
quemContraFlorResto
quemNegouFlor
pontosFlorRobo
pontosFlorHumano
quemGanhouFlor
tentosFlor
quemEscondeuPontosEnvido
quemEscondeuPontosFlor
quemTruco
quandoTruco
quemRetruco
quandoRetruco
quemValeQuatro
quandoValeQuatro
quemNegouTruco
quemGanhouTruco
tentosTruco
tentosAnterioresRobo
tentosAnterioresHumano
tentosPosterioresRobo
tentosPosterioresHumano
roboMentiuEnvido
humanoMentiuEnvido
roboMentiuFlor
humanoMentiuFlor
roboMentiuTruco
humanoMentiuTruco
quemBaralho
quandoBaralho
quemContraFlorFalta
quemEnvidoEnvido
quemFlorFlor
quandoCartaVirada
nai

In [120]:
df.primeiraCartaRobo

idMao
52       6
56       8
68      24
69       3
77       1
        ..
7633     3
7668     2
7700     3
7706     2
7717     8
Name: primeiraCartaRobo, Length: 2453, dtype: int64

Métricas estatísticas de todas as colunas da base de casos

In [121]:
df.describe().T

count       mean        std  min   25%   50%  \
jogadorMao                      2453.0   1.417448   0.493239  1.0   1.0   1.0   
cartaAltaRobo                   2453.0  30.007746  15.037133  3.0  16.0  24.0   
cartaMediaRobo                  2453.0  12.718712   9.340485  1.0   7.0   8.0   
cartaBaixaRobo                  2453.0   3.916429   3.178606  1.0   2.0   3.0   
cartaAltaHumano                 2453.0  21.547085  14.927828  0.0   8.0  16.0   
...                                ...        ...        ...  ...   ...   ...   
quantidadeChamadasEnvidoRobo    2453.0   0.008969   0.094296  0.0   0.0   0.0   
quantidadeChamadasEnvidoHumano  2453.0   0.000815   0.028548  0.0   0.0   0.0   
saldoTruco                      2453.0   2.262128   0.874333  1.0   2.0   2.0   
saldoEnvido                     2453.0   0.831635   1.508738  0.0   0.0   1.0   
saldoFlor                       2453.0   0.000000   0.000000  0.0   0.0   0.0   

                                 75%   max  
jogadorMao                       2.0   2.0  
cartaAltaRobo                   42.0  52.0  
cartaMediaRobo                  16.0  50.0  
cartaBaixaRobo                   6.0  24.0  
cartaAltaHumano                 24.0  52.0  
...                              ...   ...  
quantidadeChamadasEnvidoRobo     0.0   1.0  
quantidadeChamadasEnvidoHumano   0.0   1.0  
saldoTruco                       3.0   4.0  
saldoEnvido                      1.0  24.0  
saldoFlor                        0.0   0.0  

[80 rows x 8 columns]

## sklearn
Avaliação das métricas da base de dados

In [122]:
from sklearn.model_selection import train_test_split

In [123]:
y = df['primeiraCartaRobo']
X = df.drop(['primeiraCartaRobo'], axis=1)

SEED = 42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=SEED)

In [124]:
len(X), len(X_train), len(X_test)

(2453, 1839, 614)

In [125]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [126]:
scaled_df = pd.DataFrame(X_train, columns=X.columns)
scaled_df.describe().T

count          mean       std       min  \
jogadorMao                      1839.0 -6.375180e-17  1.000272 -0.838318   
cartaAltaRobo                   1839.0 -8.307052e-17  1.000272 -1.803681   
cartaMediaRobo                  1839.0 -7.727490e-18  1.000272 -1.267829   
cartaBaixaRobo                  1839.0  5.216056e-17  1.000272 -0.915180   
cartaAltaHumano                 1839.0  9.659363e-17  1.000272 -1.438573   
...                                ...           ...       ...       ...   
quantidadeChamadasEnvidoRobo    1839.0  8.693427e-18  1.000272 -0.104857   
quantidadeChamadasEnvidoHumano  1839.0  1.352311e-17  1.000272 -0.023325   
saldoTruco                      1839.0 -1.188102e-16  1.000272 -1.444159   
saldoEnvido                     1839.0  4.250120e-17  1.000272 -0.604168   
saldoFlor                       1839.0  0.000000e+00  0.000000  0.000000   

                                     25%       50%       75%        max  
jogadorMao                     -0.838318 -0.838318  1.192864   1.192864  
cartaAltaRobo                  -0.931006 -0.393976  0.814343   1.485631  
cartaMediaRobo                 -0.610934 -0.501452  0.374407   4.096809  
cartaBaixaRobo                 -0.598288 -0.281395  0.669283   6.373348  
cartaAltaHumano                -0.903973 -0.369373  0.165227   2.036328  
...                                  ...       ...       ...        ...  
quantidadeChamadasEnvidoRobo   -0.104857 -0.104857 -0.104857   9.536771  
quantidadeChamadasEnvidoHumano -0.023325 -0.023325 -0.023325  42.871902  
saldoTruco                     -0.315948 -0.315948  0.812263   1.940474  
saldoEnvido                    -0.604168  0.130178  0.130178  17.020119  
saldoFlor                       0.000000  0.000000  0.000000   0.000000  

[79 rows x 8 columns]

In [127]:
from sklearn.neighbors import KNeighborsRegressor

In [128]:
regressor = KNeighborsRegressor(n_neighbors=5)
regressor.fit(X_train, y_train)

KNeighborsRegressor()

In [129]:
y_pred = regressor.predict(X_test)

Verificação do Mean Absolute Error (MAE), Mean Squared Error (MSE) Root Mean Squared Error (RMSE)
* MAE é usada para avaliar os erros entre as observações;
* MSE é usada para avaliar o viés e a variação;
* RMSE é utilizada para verificar a acurácia do modelo, ao realizar a raiz quadrada do MSE.

In [130]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print(f'mae: {mae}')
print(f'mse: {mse}')
print(f'rmse: {rmse}')

mae: 3.698697068403909
mse: 36.34651465798046
rmse: 6.028807067569874


Coeficiente de determinação da predição

In [131]:
regressor.score(X_test, y_test)

0.5699318004429462

In [132]:
y.describe()

count    2453.000000
mean        8.295149
std         9.330315
min         1.000000
25%         2.000000
50%         6.000000
75%         8.000000
max        52.000000
Name: primeiraCartaRobo, dtype: float64

## Teste com casos da própria base

In [133]:
X

jogadorMao  cartaAltaRobo  cartaMediaRobo  cartaBaixaRobo  \
idMao                                                              
52              2             24              12               6   
56              2             42              24               8   
68              1             24              24               4   
69              2             42               8               3   
77              1             16              12               1   
...           ...            ...             ...             ...   
7633            1             24               8               3   
7668            2             52              40               2   
7700            1             50              12               3   
7706            2             24               4               2   
7717            1             52              24               8   

       cartaAltaHumano  cartaMediaHumano  cartaBaixaHumano  \
idMao                                                        
52                  16                 4                 3   
56                  52                16                 7   
68                  24                 8                 6   
69                  24                12                 2   
77                   6                 2                 1   
...                ...               ...               ...   
7633                50                12                 4   
7668                24                24                 8   
7700                40                16                 2   
7706                24                12                 3   
7717                42                24                12   

       primeiraCartaHumano  segundaCartaRobo  segundaCartaHumano  ...  \
idMao                                                             ...   
52                       4                12                  16  ...   
56                       7                24                  52  ...   
68                       6                 4                   8  ...   
69                       2                 8                  12  ...   
77                       2                12                   6  ...   
...                    ...               ...                 ...  ...   
7633                    50                24                  12  ...   
7668                    24                40                  24  ...   
7700                    40                50                  16  ...   
7706                    24                24                  12  ...   
7717                    42                52                  24  ...   

       naipeTerceiraCartaHumano  quantidadeChamadasHumano  \
idMao                                                       
52                            3                         1   
56                            3                         0   
68                            4                         0   
69                            3                         1   
77                            0                         0   
...                         ...                       ...   
7633                          3                         0   
7668                          1                         0   
7700                          4                         0   
7706                          1                         0   
7717                          2                         0   

       quantidadeChamadasRobo  qualidadeMaoRobo  qualidadeMaoHumano  \
idMao                                                                 
52                          0                42                  23   
56                          1                74                  75   
68                          1                52                  38   
69                          0                53                  38   
77                          0                29                   9   
...                       ...               ...                 ...   
763

In [138]:
X.iloc[0]

jogadorMao                         2
cartaAltaRobo                     24
cartaMediaRobo                    12
cartaBaixaRobo                     6
cartaAltaHumano                   16
                                  ..
quantidadeChamadasEnvidoRobo       0
quantidadeChamadasEnvidoHumano     0
saldoTruco                         2
saldoEnvido                        3
saldoFlor                          0
Name: 52, Length: 79, dtype: int64

In [140]:
X

jogadorMao  cartaAltaRobo  cartaMediaRobo  cartaBaixaRobo  \
idMao                                                              
52              2             24              12               6   
56              2             42              24               8   
68              1             24              24               4   
69              2             42               8               3   
77              1             16              12               1   
...           ...            ...             ...             ...   
7633            1             24               8               3   
7668            2             52              40               2   
7700            1             50              12               3   
7706            2             24               4               2   
7717            1             52              24               8   

       cartaAltaHumano  cartaMediaHumano  cartaBaixaHumano  \
idMao                                                        
52                  16                 4                 3   
56                  52                16                 7   
68                  24                 8                 6   
69                  24                12                 2   
77                   6                 2                 1   
...                ...               ...               ...   
7633                50                12                 4   
7668                24                24                 8   
7700                40                16                 2   
7706                24                12                 3   
7717                42                24                12   

       primeiraCartaHumano  segundaCartaRobo  segundaCartaHumano  ...  \
idMao                                                             ...   
52                       4                12                  16  ...   
56                       7                24                  52  ...   
68                       6                 4                   8  ...   
69                       2                 8                  12  ...   
77                       2                12                   6  ...   
...                    ...               ...                 ...  ...   
7633                    50                24                  12  ...   
7668                    24                40                  24  ...   
7700                    40                50                  16  ...   
7706                    24                24                  12  ...   
7717                    42                52                  24  ...   

       naipeTerceiraCartaHumano  quantidadeChamadasHumano  \
idMao                                                       
52                            3                         1   
56                            3                         0   
68                            4                         0   
69                            3                         1   
77                            0                         0   
...                         ...                       ...   
7633                          3                         0   
7668                          1                         0   
7700                          4                         0   
7706                          1                         0   
7717                          2                         0   

       quantidadeChamadasRobo  qualidadeMaoRobo  qualidadeMaoHumano  \
idMao                                                                 
52                          0                42                  23   
56                          1                74                  75   
68                          1                52                  38   
69                          0                53                  38   
77                          0                29                   9   
...                       ...               ...                 ...   
763

In [165]:
samples = [[0., 0., 0.], [0., .5, 0.], [1., 1., .5]]
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=20)
neigh.fit(X.values)
print(neigh.kneighbors([X.iloc[0]]))

(array([[ 0.        , 25.96150997, 26.81417536, 27.5680975 , 28.61817604,
        31.30495168, 36.18010503, 37.76241518, 39.26830783, 39.40812099,
        40.29888336, 41.6533312 , 43.66921112, 44.59820624, 44.65422712,
        45.22167622, 45.98912915, 46.16275555, 46.7653718 , 48.11444689]]), array([[ 0, 21, 36, 27,  4, 20, 23, 12, 37, 15, 13, 34,  3, 11, 33,  6,
         2, 24, 18, 29]]))


In [166]:
teste = X.iloc[0].to_numpy().reshape(1, -1)
teste
neigh.kneighbors(teste, return_distance=False)

array([[ 0, 21, 36, 27,  4, 20, 23, 12, 37, 15, 13, 34,  3, 11, 33,  6,
         2, 24, 18, 29]])

In [154]:
teste

array([[ 2, 24, 12,  6, 16,  4,  3,  4, 12, 16, 24,  3,  1,  2,  1,  0,
         0,  0,  3,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  2,  2,  0,  0,  0,  0,  0,  1,  2,  9,  4, 11,  4,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  2,  4,  2,
         3,  4,  2,  2,  1,  3,  1,  0, 42, 23,  0,  0,  2,  3,  0]])

In [156]:
X.iloc[21].to_numpy().reshape(1, -1)

array([[ 2, 24,  7,  1,  8,  4,  3,  3,  1,  4, 24,  8,  1,  2,  1,  0,
         0,  0,  4,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1,  1,  2,  2,  1,  3,  0,  1,  4, 12,  7, 16,  7,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  3,  1,  3,  4,  3,
         3,  2,  1,  4,  2,  3,  0,  1, 32, 15,  0,  0,  4,  1,  0]])

In [157]:
X.iloc[36].to_numpy().reshape(1, -1)

array([[ 1, 24,  7,  2, 16,  7,  1, 16,  2,  1, 24,  0,  2,  1,  1,  0,
         0,  0,  5,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  2,  2,  0,  0,  0,  0,  1,  1,  3, 12,  2, 15,  2,  0,  0,
         0,  0,  0,  0,  2,  2,  0,  0,  0,  0,  4,  1,  3,  2,  3,  2,
         1,  2,  3,  3,  4,  0,  0,  1, 33, 24,  0,  0,  3,  5,  0]])

In [158]:
X.iloc[90].to_numpy().reshape(1, -1)

array([[ 1, 42, 16,  7, 16,  7,  7,  7,  7, 16, 42,  7,  1,  2,  1,  1,
         0,  0, 27, 22,  0,  1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  2,
         0,  1,  2,  2,  3,  1,  3,  0,  1,  4, 13,  9, 19,  9,  0,  4,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  3,  1,  4,  3,  4,
         3,  4,  1,  4,  1,  3,  0,  0,  0,  0,  0,  0,  4,  2,  0]])